
services:
  backend:
    build: .
    container_name: fastapi_app
    working_dir: /app/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"

  frontend:
    build: .
    container_name: streamlit_app
    working_dir: /app/streamlit_app
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - ./streamlit_app:/app/streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - backend
